### ISSUE TITLE
Fail to work in OS 10.11

### ISSUE THREAD

**Issue by lisai9093** [the-darkvoid/BrcmPatchRAM#19] opened 2015-06-09 09:41 UTC
Bluetooth is grey out showing: bluetooth unavailable.

Any idea?

Thx.

**Comment by mariusvictorbach** [comment] 2015-06-10 11:14
Sounds like "early adopters syndrome" ;-)

**Comment by theracermaster** [comment] 2015-06-16 02:41
Look here: http://www.insanelymac.com/forum/topic/306632-broadcom-bluetooth-20702a/#entry2144734

**Comment by RehabMan** [comment] 2015-06-17 22:19
Duplicate of https://github.com/RehabMan/OS-X-BrcmPatchRAM/issues/3

**Comment by RehabMan** [comment] 2015-06-24 18:33
Use BrcmBluetoothInjector.kext from my fork of this repo.

**Comment by RehabMan** [comment] 2015-09-15 15:21
BrcmPatchRAM2.kext is available for testing.

https://bitbucket.org/RehabMan/os-x-brcmpatchram/downloads

**Comment by the-darkvoid** [comment] 2015-09-17 05:00
Closed with usbhost branch and pull request #24.

**Closed by the-darkvoid** 2015-09-17 05:01 UTC
